// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

/** Base do projeto; Edge Functions usam a mesma URL: `${SUPABASE_URL}/functions/v1/<nome>`. */
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
/** Anon/public key — aceita nome usado no Dashboard (anon) ou publishable do .env.example */
const SUPABASE_ANON_OR_PUBLISHABLE =
  (import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined) ||
  (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined) ||
  '';

const ESCALAX_EXPECTED_PROJECT_REF = 'fbryqzwykdhnmskfectg';

/**
 * Fallbacks só para o construtor não lançar (supabase-js exige URL https e chave não vazia).
 * Sem variáveis corretas no deploy, a API falhará — mas a shell da app renderiza e o envCheck avisa no console.
 */
const FALLBACK_SUPABASE_URL = `https://${ESCALAX_EXPECTED_PROJECT_REF}.supabase.co`;
/** JWT demo formato válido (não é segredo); substituído quando VITE_SUPABASE_ANON_KEY existe. */
const FALLBACK_ANON_PLACEHOLDER =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0';

function deriveProjectRefFromUrl(url: string | undefined): string | null {
  if (!url?.trim()) return null;
  try {
    const m = new URL(url.trim()).hostname.toLowerCase().match(/^([a-z0-9]+)\.supabase\.co$/);
    return m ? m[1] : null;
  } catch {
    return null;
  }
}

const resolvedUrl = SUPABASE_URL?.trim() || FALLBACK_SUPABASE_URL;
const resolvedKey = String(SUPABASE_ANON_OR_PUBLISHABLE).trim() || FALLBACK_ANON_PLACEHOLDER;

if (import.meta.env.DEV) {
  const ref = deriveProjectRefFromUrl(SUPABASE_URL);
  const hasAnon = !!(import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined)?.trim();
  const hasPublishable = !!(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined)?.trim();
  const hasAnyKey = !!(SUPABASE_ANON_OR_PUBLISHABLE && String(SUPABASE_ANON_OR_PUBLISHABLE).trim());

  console.info('[EscalaX Supabase] URL in use:', SUPABASE_URL ?? '(ausente)');
  console.info('[EscalaX Supabase] derived project ref:', ref ?? '(inválido ou ausente)');
  if (!SUPABASE_URL?.trim()) {
    console.warn('[EscalaX Supabase] VITE_SUPABASE_URL ausente — defina em .env.local');
  }
  if (!hasAnon && !hasPublishable) {
    console.warn(
      '[EscalaX Supabase] VITE_SUPABASE_ANON_KEY e VITE_SUPABASE_PUBLISHABLE_KEY ausentes — preencha no .env.local (Dashboard → API).',
    );
  }
  if (ref && ref !== ESCALAX_EXPECTED_PROJECT_REF) {
    console.warn(
      '[EscalaX Supabase] URL aponta para outro project ref que o esperado para EscalaX. Esperado:',
      ESCALAX_EXPECTED_PROJECT_REF,
      '— obtido:',
      ref,
      '— suporte/Edge Functions usarão o projeto da URL acima.',
    );
  }
  if (SUPABASE_URL?.trim() && hasAnyKey) {
    console.info('[EscalaX Supabase] chave pública configurada (comprimento:', String(SUPABASE_ANON_OR_PUBLISHABLE).length, 'chars)');
  }
}

if (import.meta.env.DEV && (!SUPABASE_URL || !SUPABASE_ANON_OR_PUBLISHABLE)) {
  console.warn(
    '[EscalaX] Defina VITE_SUPABASE_URL e VITE_SUPABASE_ANON_KEY (ou VITE_SUPABASE_PUBLISHABLE_KEY) no .env.local — Edge Functions e auth não funcionarão sem isso.',
  );
}

let supabaseInstance: ReturnType<typeof createClient<Database>>;
try {
  supabaseInstance = createClient<Database>(resolvedUrl, resolvedKey, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      /** Sessão a partir de hash/query é tratada em `/auth/callback` (evita corrida com AuthProvider). */
      detectSessionInUrl: false,
    },
  });
} catch (e) {
  console.error('[EscalaX] createClient falhou — a usar fallbacks mínimos:', e);
  supabaseInstance = createClient<Database>(FALLBACK_SUPABASE_URL, FALLBACK_ANON_PLACEHOLDER, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: false,
    },
  });
}

export const supabase = supabaseInstance;

console.log('[EscalaX boot] supabase client init ok');

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
